// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('./src/views/iview/components/AddForm.vue')['default']
    AddFormEl: typeof import('./src/views/elem/components/AddFormEl.vue')['default']
    AddFormVs: typeof import('./src/views/vuesax/components/AddFormVs.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElPopconfirm: typeof import('element-ui/lib/popconfirm')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    IButton: typeof import('view-design/src/components/button')['default']
    IDivider: typeof import('view-design/src/components/divider')['default']
    IForm: typeof import('view-design/src/components/form')['default']
    IFormItem: typeof import('view-design/src/components/form-item')['default']
    IInput: typeof import('view-design/src/components/input')['default']
    ITable: typeof import('view-design/src/components/table')['default']
    Template: typeof import('./src/views/iview/template.vue')['default']
    TemplateEl: typeof import('./src/views/elem/template-el.vue')['default']
    TemplateSetup: typeof import('./src/views/iview/template-setup.vue')['default']
    TemplateVs: typeof import('./src/views/vuesax/template-vs.vue')['default']
    TodoTable: typeof import('./src/views/iview/components/TodoTable.vue')['default']
    TodoTableEl: typeof import('./src/views/elem/components/TodoTableEl.vue')['default']
    TodoTableVs: typeof import('./src/views/vuesax/components/TodoTableVs.vue')['default']
    Undefined: typeof import('./src/views/index.vue')['default']
    VsButton: typeof import('vuesax/dist/vsButton')['default']
    VsCheckbox: typeof import('vuesax/dist/vsCheckbox')['default']
    VsInput: typeof import('vuesax/dist/vsInput')['default']
    VsNavbar: typeof import('vuesax/dist/vsNavbar')['default']
    VsNavbarItem: typeof import('vuesax/dist/vsNavbarItem')['default']
    VsTable: typeof import('vuesax/dist/vsTable')['default']
    VsTd: typeof import('vuesax/dist/vsTableTd')['default']
    VsTh: typeof import('vuesax/dist/vsTableTh')['default']
    VsTooltip: typeof import('vuesax/dist/vsTooltip')['default']
    VsTr: typeof import('vuesax/dist/vsTableTr')['default']
  }
}

export { }
