// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    IButton: typeof import('view-design/src/components/button')['default']
    IDivider: typeof import('view-design/src/components/divider')['default']
    VsNavbar: typeof import('vuesax/dist/vsNavbar')['default']
    VsNavbarItem: typeof import('vuesax/dist/vsNavbarItem')['default']
  }
}

export { }
