// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    SrcApp: typeof import('./src/App.vue')['default']
    SrcComponentsATest: typeof import('./src/components/ATest.vue')['default']
    SrcComponentsBTest: typeof import('./src/components/BTest.vue')['default']
    SrcViewsAntdComponentsAddForm: typeof import('./src/views/antd/components/AddForm.vue')['default']
    SrcViewsAntdComponentsAddFormTsx: typeof import('./src/views/antd/components/AddFormTsx.vue')['default']
    SrcViewsAntdComponentsInfoDrawer: typeof import('./src/views/antd/components/InfoDrawer.vue')['default']
    SrcViewsAntdComponentsTodoList: typeof import('./src/views/antd/components/TodoList.vue')['default']
    SrcViewsAntdComponentsTodoTable: typeof import('./src/views/antd/components/TodoTable.vue')['default']
    SrcViewsAntdComponentsTodoTableTmpl: typeof import('./src/views/antd/components/TodoTableTmpl.vue')['default']
    SrcViewsAntdDefineTsx: typeof import('./src/views/antd/define-tsx.vue')['default']
    SrcViewsAntdScriptTmpl: typeof import('./src/views/antd/script-tmpl.vue')['default']
    SrcViewsAntdScriptTsx: typeof import('./src/views/antd/script-tsx.vue')['default']
    SrcViewsElemComponentsAddForm: typeof import('./src/views/elem/components/AddForm.vue')['default']
    SrcViewsElemComponentsTodoList: typeof import('./src/views/elem/components/TodoList.vue')['default']
    SrcViewsElemComponentsTodoTable: typeof import('./src/views/elem/components/TodoTable.vue')['default']
    SrcViewsElemDefineTmpl: typeof import('./src/views/elem/define-tmpl.vue')['default']
    SrcViewsLayuiComponentsAddFormLay: typeof import('./src/views/layui/components/AddFormLay.vue')['default']
    SrcViewsLayuiComponentsTodoTableLay: typeof import('./src/views/layui/components/TodoTableLay.vue')['default']
    SrcViewsLayuiTmpl: typeof import('./src/views/layui/tmpl.vue')['default']
    SrcViewsNaiveComponentsAddForm: typeof import('./src/views/naive/components/AddForm.vue')['default']
    SrcViewsNaiveComponentsTodoList: typeof import('./src/views/naive/components/TodoList.vue')['default']
    SrcViewsNaiveComponentsTodoTable: typeof import('./src/views/naive/components/TodoTable.vue')['default']
    SrcViewsNaiveDefineTmpl: typeof import('./src/views/naive/define-tmpl.vue')['default']
  }
}

export { }
