// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    AButton: typeof import('ant-design-vue/es')['Button']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AList: typeof import('ant-design-vue/es')['List']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AForm: typeof import('ant-design-vue/es')['Form']
    ATable: typeof import('ant-design-vue/es')['Table']
    ElButton: typeof import('element-plus/lib/el-button')['default']
    ElDivider: typeof import('element-plus/lib/el-divider')['default']
    ElCheckbox: typeof import('element-plus/lib/el-checkbox')['default']
    ElTableColumn: typeof import('element-plus/lib/el-table-column')['default']
    ElInput: typeof import('element-plus/lib/el-input')['default']
    ElPopconfirm: typeof import('element-plus/lib/el-popconfirm')['default']
    ElTable: typeof import('element-plus/lib/el-table')['default']
  }
}

export { }
