// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    AButton: typeof import('ant-design-vue/es')['Button']
    AStatisticCountdown: typeof import('ant-design-vue/es')['StatisticCountdown']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AForm: typeof import('ant-design-vue/es')['Form']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AList: typeof import('ant-design-vue/es')['List']
    ATable: typeof import('ant-design-vue/es')['Table']
  }
}

export { }
